require:
#  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
#  - rubocop-rspec_rails

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 3.3
  TargetRailsVersion: 7.2
  NewCops: enable
  Exclude:
    - "spec/dummy/db/schema.rb"

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: around

Layout/IndentationConsistency:
  EnforcedStyle: normal

Style/SymbolArray:
  EnforcedStyle: percent

Style/WordArray:
  EnforcedStyle: percent

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/SafeNavigationChainLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

RSpec/NestedGroups:
  Max: 5

RSpec/ExampleLength:
  Max: 10

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
