require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-factory_bot

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: around

Layout/IndentationConsistency:
  EnforcedStyle: normal

Style/SymbolArray:
  EnforcedStyle: percent

Style/WordArray:
  EnforcedStyle: percent

Style/MethodCallWithArgsParentheses:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

RSpec/ExampleLength:
  Max: 10

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Rails/Date:
  Enabled: false
