plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-rspec_rails

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 3.4
  TargetRailsVersion: 8.1
  NewCops: enable
  Exclude:
    - "spec/dummy/db/schema.rb"

Layout/LineLength:
  Enabled: true
  Max: 120

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: around

Layout/IndentationConsistency:
  EnforcedStyle: normal

Style/SymbolArray:
  EnforcedStyle: percent

Style/WordArray:
  EnforcedStyle: percent

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/SafeNavigationChainLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

RSpec/NestedGroups:
  Max: 5

RSpec/ExampleLength:
  Max: 10

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Naming/InclusiveLanguage:
  Enabled: false
